---
apiVersion: charts.helm.k8s.io/v1
kind: Xl
metadata:
  name: xl-release
spec:
  # This configuration file is used for production.
  # Default values copied from <project_dir>/helm-charts/xl/values.yaml

  # Default values for xl.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  # Any changes run : kubectl apply -f deploy/crds/charts_v1_xl_cr.yaml -n turbonomic

  # Global settings
  global:
    #  registry: index.docker.io
    #  imageUsername: turbouser
    #  imagePassword: turbopassword
    repository: icr.io/cpopen/turbonomic
    tag: 8.17.6
    # If using an external database server with Turbonomic, then
    # specify either the externalDbIP (with the IP address) or
    # the externalDBName (with fully qualified domain name (FQDN)) of the external DB.
    externalDbIP: 10.0.2.15
    # externalDBName:

    # provide the correct annotations based on the LB you want and the properties you want
    # ingress:
      # annotations:
        # networking.gke.io/load-balancer-type: "Internal"
    # To use the default storage class in the deployment, remove the storageClassName property.
    # To specify a non-default storage class, include the storageClassName property as shown below.
    storageClassName: standard-rwo-retain
    # Hosting modes for component: self-hosted, saas
    #hostingMode: self-hosted
    # Hosting Provider for a component: gcp
    hostingProvider: gcp
    # Offering by the hosting provider: gke
    hostingPlatform: gke
    # Hosting Region of a component: us-central1 etc
    #hostingRegion: us-central1

  # Component selector - Probes can be enabled based on the requirement
  actionscript:
    enabled: false
  actionstream-kafka:
    enabled: false
  appdynamics:
    enabled: false
  aws:
    enabled: false
  azure:
    enabled: false
    metrics:
      enabled: false
  dynatrace:
    enabled: false
  gcp:
    enabled: true
  hpe3par:
    enabled: false
  horizon:
    enabled: false
  hyperflex:
    enabled: false
  hyperv:
    enabled: false
  ibmstorage-flashsystem:
    enabled: false
  kubeturbo:
    enabled: false
  netapp:
    enabled: false
  nutanix:
    enabled: false
  oneview:
    enabled: false
  prometheus-mysql-exporter:
    enabled: false
  prometheus:
    enabled: false
  prometurbo:
    enabled: false
  pure:
    enabled: false
  scaleio:
    enabled: false
  servicenow:
    enabled: false
  ucs:
    enabled: false
  vcenter:
    enabled: false
  vmax:
    enabled: false
  vmm:
    enabled: false
  wmi:
    enabled: false
  snmp:
    enabled: false
  mssql:
    enabled: false
  mysql:
    enabled: false
  oracle:
    enabled: false
  tomcat:
    enabled: false
  jvm:
    enabled: false
  newrelic:
    enabled: false
  udt:
    enabled: false
  websphere:
    enabled: false
  weblogic:
    enabled: false
  xen:
    enabled: false
  instana:
    enabled: false
  datadog:
    enabled: false
  powervm:
    enabled: false
